---
- name: install web servers 
  hosts: webservers
  roles:
    - role: web_servers
    - tags: setup_apache-web_servers


- name : install loadbalancers
  hosts : loadbalancers
  roles : 
    - role: balancers 
    - tags: setup_nginx-Loadbalancers


- name : install mongodb
  hosts : db
  roles : 
   - role: db
   - tags: setup_mongodb_hosts