
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest
 
    - name: confiure root for host variable
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
 
    - name: push index file
      template:
        src: "templates/index-template.html"
        dest: "/var/www/{{ http_host }}/index.html"
 
    - name: Set up virtuahHost
      template:
        src: "templates/apache-template.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
 
    - name: Enable site
      command: a2ensite {{ http_conf }}
      notify: restart-apache
 
    - name: Allow https connections
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 80
      ctstate: NEW
      syn: match
      jump: ACCEPT

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted


