vars:
  haproxy_app_name: example
  haproxy_mode: http
  haproxy_enable_stats: enable 
  haproxy_algorithm: roundrobin
  haproxy_backend_servers:
    - {name: server1, ip: xx.xx.xx.xx, port: 80, paramstring: cookie A check}
    - {name: server2, ip: xx.xx.xx.xx, port: 80, paramstring: cookie A check}
    haproxy_stats_users:
    - {username: SomeUser, password: SomePAssword}

tasks:
    - name: install haproxy
      apt: name=haproxy state=present
      
    - name: Enable init script
      replace: dest='/etc/default/haproxy' 
         regexp='ENABLED=0'
         replace='ENABLED=1'
    
    
    - name: Update HAProxy config
      template: src=templates/haproxy.cfg 
          dest=/etc/haproxy/haproxy.cfg 
          backup=yes

handlers:
- name: restart haproxy
  service: name=haproxy state=restarted